apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file ../docker/docker-compose.yml convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: stellar-core
  name: stellar-core
spec:
  ports:
  - name: "11625"
    port: 11625
    targetPort: 11625
  - name: "11626"
    port: 11626
    targetPort: 11626
  selector:
    io.kompose.service: stellar-core
status:
  loadBalancer: {}
