# example docker compose file for how to run stellar core
version: '3'
services:
  stellar-core-postgres:
    image: postgres:9
    restart: on-failure
    environment:
      - POSTGRES_DB=stellar-core

  stellar-core:
    image: satoshipay/stellar-core:10.2.0
    restart: always
    ports:
    - 11625:11625
    - 11626:11626
    environment:
      - DATABASE=postgresql://dbname=stellar-core user=postgres password=DATABASE_PASSWORD host=stellar-core-postgres
      - DATABASE_PASSWORD=2aq853RGDqdHAWFwGDSGGRIUP9VzJJsh
      # WARNING: make sure to use a new NODE_SEED!
      # public key GD4E3XVLEBB4JMR7KNNMTSGXIKOK56ZZXX764KEPKE4IR73DEG6O22SI
      - NODE_SEED=SCBQ3PUIFODWT3IH2H36IB7ZWT2FKNZQTS6ZZ3QIXS63IFIXZEGRTBUM my_stellar_node
      - NODE_IS_VALIDATOR=false
      - NETWORK_PASSPHRASE=Test SDF Network ; September 2015
      - UNSAFE_QUORUM=true
      - FAILURE_SAFETY=1
      - RUN_STANDALONE=false
      - CATCHUP_RECENT=60480
      - MAX_PEER_CONNECTIONS=30
      - "KNOWN_PEERS=\
        core-testnet1.stellar.org,\
        core-testnet2.stellar.org,\
        core-testnet3.stellar.org"
      - "PREFERRED_PEERS=\
        core-testnet1.stellar.org,\
        core-testnet2.stellar.org,\
        core-testnet3.stellar.org"
      - "NODE_NAMES=\
        GDKXE2OZMJIPOSLNA6N6F2BVCI3O777I2OOC4BV7VOYUEHYX7RTRYA7Y sdf1,\
        GCUCJTIYXSOXKBSNFGNFWW5MUQ54HKRPGJUTQFJ5RQXZXNOLNXYDHRAP sdf2,\
        GC2V2EFSXN6SQTWVYA5EPJPBWWIMSD2XQNKUOHGEKB535AQE2I6IXV2Z sdf3"
       # this is just an example quorum set – you most likely want to change it
      - >-
          QUORUM_SET=[
            {
              "threshold_percent": 51,
              "validators": [
                "$$sdf1",
                "$$sdf2",
                "$$sdf3"
              ]
            }
          ]
      - >-
          HISTORY={
            "h1": {"get": "curl -sf http://history.stellar.org/prd/core-testnet/core_testnet_001/{0} -o {1}"},
            "h2": {"get": "curl -sf http://history.stellar.org/prd/core-testnet/core_testnet_002/{0} -o {1}"},
            "h3": {"get": "curl -sf http://history.stellar.org/prd/core-testnet/core_testnet_003/{0} -o {1}"}
          }

  stellar-horizon-postgres:
    image: postgres:9
    restart: on-failure
    environment:
      - POSTGRES_DB=stellar-horizon

  stellar-horizon:
    image: satoshipay/stellar-horizon:0.17.2
    restart: on-failure
    ports:
    - 8000:8000
    environment:
      - DATABASE_URL=postgres://postgres@stellar-horizon-postgres/stellar-horizon?sslmode=disable
      - STELLAR_CORE_DATABASE_URL=postgres://postgres@stellar-core-postgres/stellar-core?sslmode=disable
      - STELLAR_CORE_URL=http://stellar-core:11626
      - NETWORK_PASSPHRASE=Test SDF Network ; September 2015
      - CURRENT_PROTOCOL_VERSION=10
      - INGEST=true
