kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-horizon-pv-volume
  labels:
    app: postgresql
    release: horizon
    role: master
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data"
---
# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: postgres-horizon-pv-claim
#   labels:
#     app: postgres-horizon
# spec:
#   storageClassName: manual
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 5Gi