apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file ../docker/docker-compose.yml convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: stellar-core
  name: stellar-core
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: stellar-core
    spec:
      containers:
      - env:
        - name: CATCHUP_RECENT
          value: "60480"
        - name: DATABASE
          value: postgresql://dbname=stellar-core user=postgres password=abcd host=postgres-sc sslmode=disable
        - name: DATABASE_PASSWORD
          value: abcd
        - name: FAILURE_SAFETY
          value: "1"
        - name: HISTORY
          value: |-
            {
              "h1": {"get": "curl -sf http://history.stellar.org/prd/core-testnet/core_testnet_001/{0} -o {1}"},
              "h2": {"get": "curl -sf http://history.stellar.org/prd/core-testnet/core_testnet_002/{0} -o {1}"},
              "h3": {"get": "curl -sf http://history.stellar.org/prd/core-testnet/core_testnet_003/{0} -o {1}"}
            }
        - name: KNOWN_PEERS
          value: core-testnet1.stellar.org,core-testnet2.stellar.org,core-testnet3.stellar.org
        - name: MAX_PEER_CONNECTIONS
          value: "30"
        - name: NETWORK_PASSPHRASE
          value: Test SDF Network ; September 2015
        - name: NODE_IS_VALIDATOR
          value: "false"
        - name: NODE_NAMES
          value: GDKXE2OZMJIPOSLNA6N6F2BVCI3O777I2OOC4BV7VOYUEHYX7RTRYA7Y sdf1,GCUCJTIYXSOXKBSNFGNFWW5MUQ54HKRPGJUTQFJ5RQXZXNOLNXYDHRAP
            sdf2,GC2V2EFSXN6SQTWVYA5EPJPBWWIMSD2XQNKUOHGEKB535AQE2I6IXV2Z sdf3
        - name: NODE_SEED
          value: SCBQ3PUIFODWT3IH2H36IB7ZWT2FKNZQTS6ZZ3QIXS63IFIXZEGRTBUM my_stellar_node
        - name: PREFERRED_PEERS
          value: core-testnet1.stellar.org,core-testnet2.stellar.org,core-testnet3.stellar.org
        - name: QUORUM_SET
          value: |-
            [
              {
                "threshold_percent": 51,
                "validators": [
                  "$sdf1",
                  "$sdf2",
                  "$sdf3"
                ]
              }
            ]
        - name: RUN_STANDALONE
          value: "false"
        - name: UNSAFE_QUORUM
          value: "true"
        image: satoshipay/stellar-core:10.2.0
        name: stellar-core
        ports:
        - containerPort: 11625
        - containerPort: 11626
        resources: {}
      restartPolicy: Always
status: {}
